apiVersion: apps/v1
kind: Deployment
metadata:
  name: vonix-app-deployment
  namespace: vonix-network
  labels:
    app: vonix-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: vonix-app
  template:
    metadata:
      labels:
        app: vonix-app
    spec:
      containers:
      - name: vonix-app
        image: vonix/network:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: vonix-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: vonix-config
              key: LOG_LEVEL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: vonix-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: vonix-config
              key: REDIS_PORT
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: vonix-config
              key: NEXTAUTH_URL
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: vonix-secrets
              key: NEXTAUTH_SECRET
        - name: TURSO_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vonix-secrets
              key: TURSO_DATABASE_URL
        - name: TURSO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: vonix-secrets
              key: TURSO_AUTH_TOKEN
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: vonix-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: vonix-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: vonix-secrets
              key: DISCORD_CLIENT_ID
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: vonix-secrets
              key: DISCORD_CLIENT_SECRET
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vonix-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-logs
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vonix-app-service
  namespace: vonix-network
  labels:
    app: vonix-app
spec:
  selector:
    app: vonix-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
